name: Update Airtel Playlist

on:
  schedule:
    - cron: '0 */7 * * *'  # Every 7 hours
  workflow_dispatch:

jobs:
  update-airtel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sports repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download latest Airtel section
        run: |
          curl -sL https://raw.githubusercontent.com/alex4528/m3u/main/artl.m3u -o airtel.m3u

      - name: Backup existing new.m3u
        run: |
          if [ ! -f new.m3u ]; then
            echo "❌ new.m3u not found!" && exit 1
          fi
          cp new.m3u original_new.m3u

      - name: Replace Airtel section
        run: |
          awk '
          BEGIN { found=0; skip=0 }
          /^###############################################Airtel/ {
            print;
            while ((getline line < "airtel.m3u") > 0) print line;
            skip=1;
            next
          }
          skip && /^###############################################/ {
            skip=0
          }
          !skip { print }
          ' original_new.m3u > new.m3u

      - name: Commit if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if ! cmp -s original_new.m3u new.m3u; then
            git add new.m3u
            git commit -m "🔄 Updated Airtel section from alex4528/m3u/artl.m3u"
            git push origin main
          else
            echo "✅ No changes to commit."
