name: Update Airtel Section

on:
  schedule:
    - cron: "0 */7 * * *"  # Every 7 hours
  workflow_dispatch:

jobs:
  update-airtel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Fetch Airtel section from alex4528 repo
      run: |
        mkdir -p tmp
        curl -s https://raw.githubusercontent.com/alex4528/m3u/artl.m3u -o tmp/artl.m3u

    - name: Replace Airtel section in new.m3u
      run: |
        # Extract top before Airtel section
        awk '/^###*Airtel/{exit} {print}' new.m3u > tmp/top.m3u

        # Extract Airtel section from downloaded file
        awk '{print}' tmp/artl.m3u > tmp/airtel.m3u

        # Extract bottom after Airtel section
        awk 'BEGIN{found=0} /^###*Airtel/{found=1; next} found && /^###/{found=0} !found {next} found {print}' new.m3u > tmp/bottom.m3u

        # Combine all into updated file
        cat tmp/top.m3u tmp/airtel.m3u tmp/bottom.m3u > tmp/new.m3u
        mv tmp/new.m3u new.m3u

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add new.m3u
        git commit -m "Auto-update Airtel section from alex4528" || echo "No changes to commit"
        git push
