name: Update Airtel Playlist

on:
  schedule:
    - cron: '0 */7 * * *'  # Every 7 hours
  workflow_dispatch:       # Allow manual run too

jobs:
  update-airtel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sports repo
        uses: actions/checkout@v4
        with:
          repository: Dhruv0045/sports
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download latest Airtel section
        run: |
          curl -sL https://raw.githubusercontent.com/alex4528/m3u/artl.m3u -o airtel.m3u

      - name: Extract existing new.m3u
        run: |
          cp new.m3u original_new.m3u

      - name: Replace Airtel section
        run: |
          awk '
          BEGIN { found=0 }
          /^###############################################Airtel/ { print; found=1; while ((getline line < "airtel.m3u") > 0) print line; skip=1; next }
          found && /^###############################################/ { found=0 }
          !found { print }
          ' original_new.m3u > new.m3u

      - name: Commit if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if ! cmp -s original_new.m3u new.m3u; then
            git add new.m3u
            git commit -m "🔄 Updated Airtel section from alex4528/m3u/artl.m3u"
            git push origin main
          else
            echo "No changes in Airtel section."
          fi
name: Update Airtel Playlist

on:
  schedule:
    - cron: '0 */7 * * *'  # Every 7 hours
  workflow_dispatch:       # Allow manual run too

jobs:
  update-airtel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sports repo
        uses: actions/checkout@v4
        with:
          repository: Dhruv0045/sports
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download latest Airtel section
        run: |
          curl -sL https://raw.githubusercontent.com/alex4528/m3u/artl.m3u -o airtel.m3u

      - name: Extract existing new.m3u
        run: |
          cp new.m3u original_new.m3u

      - name: Replace Airtel section
        run: |
          awk '
          BEGIN { found=0 }
          /^###############################################Airtel/ { print; found=1; while ((getline line < "airtel.m3u") > 0) print line; skip=1; next }
          found && /^###############################################/ { found=0 }
          !found { print }
          ' original_new.m3u > new.m3u

      - name: Commit if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if ! cmp -s original_new.m3u new.m3u; then
            git add new.m3u
            git commit -m "🔄 Updated Airtel section from alex4528/m3u/artl.m3u"
            git push origin main
          else
            echo "No changes in Airtel section."
          fi
