name: Update new.m3u from artl.m3u

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Download artl.m3u
        run: |
          curl -L https://raw.githubusercontent.com/alex4528/m3u/refs/heads/main/artl.m3u -o new.m3u

      - name: Configure git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit and push if new.m3u changed
        run: |
          git remote set-url origin https://${GH_PAT}@github.com/Dhruv0045/sports.git

          if ! git diff --quiet Dhruv.m3u; then
            git add new.m3u
            git commit -m "Update new.m3u from alex4528/m3u"
            git push origin main
          else
            echo "No changes in new.m3u"
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
