name: Update Airtel Section

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  update-airtel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Airtel section from alex4528/m3u
        run: |
          curl -s https://raw.githubusercontent.com/alex4528/m3u/main/artl.m3u > airtel_new.m3u

      - name: Extract Airtel section from new file
        run: |
          sed -n '/^###############################################Airtel/,/^###############################################/p' airtel_new.m3u | sed '$d' > extracted_airtel.m3u

      - name: Backup current Dhruv.m3u
        run: cp Dhruv.m3u Dhruv_old.m3u

      - name: Replace Airtel section in Dhruv.m3u
        run: |
          awk '
            BEGIN { skip=0 }
            /^###############################################Airtel/ {
              print; skip=1;
              while (getline > 0) {
                if ($0 ~ /^###############################################/) break;
              }
              print ""; next
            }
            { if (!skip) print }
          ' Dhruv_old.m3u > temp.m3u
          cat temp.m3u extracted_airtel.m3u > Dhruv.m3u

      - name: Commit and push changes if any
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Dhruv.m3u
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
            exit 0
          fi
          git commit -m "🔄 Update Airtel section from alex4528"
          git push https://x-access-token:${GH_PAT}@github.com/Dhruv0045/sports.git HEAD:main
