name: Auto-Update FanCode Playlist

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Fetch JSON and Update M3U
        run: |
          python update_playlist.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fancode.m3u
          git commit -m "Auto-updated FanCode M3U" || echo "No changes to commit"
          git push
