name: Update Airtel Section

on:
  schedule:
    - cron: '0 */7 * * *'  # Every 7 hours
  workflow_dispatch:      # Allow manual run

jobs:
  update-airtel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Download new Airtel section
      run: |
        curl -sL https://raw.githubusercontent.com/alex4528/m3u/artl.m3u -o airtel.m3u

    - name: Extract Airtel section from source
      run: |
        awk '/^#*Airtel/{p=1; print; next} /^#/{if(p){exit}} p' airtel.m3u > airtel_section.m3u

    - name: Replace Airtel section in new.m3u
      run: |
        awk '
          BEGIN {p=1}
          /^#*Airtel/ {print_file("airtel_section.m3u"); p=0; skip=1}
          /^#/{if (skip && p==0) {p=1; skip=0; next}}
          p {print}
          function print_file(f) {
            while ((getline line < f) > 0) print line
            close(f)
          }
        ' sports/new.m3u > sports/new_updated.m3u

        mv sports/new_updated.m3u sports/new.m3u

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sports/new.m3u
        git commit -m "🔄 Auto-update Airtel section from alex4528/m3u"
        git push
