name: Auto Update from alex4528

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download artl.m3u from alex4528 repo
        run: |
          curl -o artl.m3u https://raw.githubusercontent.com/alex4528/m3u/main/artl.m3u

      - name: Check if file has changed
        id: check_diff
        run: |
          if [ ! -f new.m3u ]; then
            echo "New file doesn't exist yet. Change detected."
            echo "changed=true" >> "$GITHUB_OUTPUT"
          elif ! cmp -s artl.m3u new.m3u; then
            echo "File has changed."
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected."
            echo "changed=false" >> "$GITHUB_OUTPUT"

      - name: Exit if no change
        if: steps.check_diff.outputs.changed == 'false'
        run: exit 0

      - name: Update file
        run: |
          cp artl.m3u new.m3u

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add new.m3u
          git commit -m "Auto-update from alex4528/artl.m3u"
          git push
