name: Update Airtel Section

on:
  schedule:
    - cron: '0 */7 * * *'  # every 7 hours
  workflow_dispatch:

jobs:
  update-airtel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download artl.m3u
        run: curl -o artl.m3u https://raw.githubusercontent.com/alex4528/m3u/main/artl.m3u

      - name: Replace Airtel section in new.m3u
        run: |
          awk 'BEGIN{p=1}
               /^###############################################Airtel/{print; p=0; while(getline){if(/^#EXTM3U/){break}}}
               p{print}
               END{while((getline k < "artl.m3u") > 0) print k}' sports/new.m3u > temp && mv temp sports/new.m3u

      - name: Commit & Push
        run: |
          git add sports/new.m3u
          git diff --cached --quiet || git commit -m "Update Airtel section from alex4528/m3u"
          git push
